from __future__ import annotations
from typing import TYPE_CHECKING, Union, Optional

from src.Enums.flying_machine_enum import FlyingMachineEnum, Range
from src.Enums.geode_enum import GeodeEnum
from src.group import Group

if TYPE_CHECKING:
    from src.cell import Cell
    from src.Analyzers.geode import Geode


class FlyingMachine:

    def __init__(self,
                 flying_machine: FlyingMachineEnum,
                 origin: Cell,  # Origin is the top left coordinate of the machine in the original rotation
                 *,
                 mirrored: bool,  # Always mirrored horizontally so it never breaks with QC
                 engine_cells: set[Cell],
                 pushed_cells: dict[int, frozenset[Cell]],
                 attached_cells: dict[int, frozenset[Cell]]):
        self.flying_machine = flying_machine
        self.origin = origin
        self.mirrored = mirrored
        self.engine_cells = engine_cells
        self.pushed_cells = pushed_cells
        self.attached_cells = attached_cells
        self.complete_footprint = (self.engine_cells
                                   | {cell
                                      for cell_group in self.pushed_cells.values()
                                      for cell in cell_group}
                                   | {cell
                                      for cell_group in self.attached_cells.values()
                                      for cell in cell_group})
        # TODO: rotation

    @staticmethod
    def try_place_machine(flying_machine: FlyingMachineEnum,
                          geode: Geode,
                          origin: Cell,  # Origin is the top left coordinate of the machine in the original rotation
                          group: Group,
                          *,
                          mirrored: bool,  # Always mirrored horizontally so it never breaks with QC
                          ) -> Optional[FlyingMachine]:
        # NOTE: This function is currently only made to work for double pushers.
        # NOTE: Changes and further abstractions will be required for other designs

        # First, we create a set of cells that the engine would occupy
        engine_cells = FlyingMachine.footprint_to_cells(geode.grid, origin, flying_machine.engine_footprint, mirrored)
        if (  # Abort if the engine cells would be out of range
                engine_cells is None
                # The engine cells occupy obsidian or blocks with ANOTHER group (no group is fine)
                or any((cell.projected_block == GeodeEnum.OBSIDIAN
                        or (cell.has_group and cell not in group.cells)) for cell in engine_cells)
                # Or if none of the engine cells are part of the group
                or not group.cells & engine_cells):
            return

        # TODO: Make code below less ugly
        # Get a mapping of the cell groups to the cell that pushes the group
        pusher_cells = {pushing_group: frozenset(FlyingMachine.footprint_to_cells(geode.grid, origin,
                                                                                  footprint, mirrored))
                        for pushing_group, footprint in flying_machine.pushed_blocks_footprints.items()}
        # Liberate the pushing cell of each group from the frozenset, then merge them into a set
        pusher_cells_set = {cell
                            for frozencells in pusher_cells.values()
                            for cell in frozencells}

        # The machine is valid if exactly one of the pushers intersects with the group
        if len(intersection_ := (pusher_cells_set & group.cells)) == 1:
            group_pushing_cell = next(iter(intersection_))
            pushing_group = next(push_group  # Inverse dictionary search
                                 for push_group, frozencell in pusher_cells.items()
                                 if group_pushing_cell in frozencell)

            pusher_cells |= {pushing_group: frozenset(group.cells)}
            #push_group_number -> pushing cell or all pushed cells
            return FlyingMachine(flying_machine, origin,
                                 mirrored=mirrored,
                                 engine_cells=engine_cells,
                                 pushed_cells=pusher_cells,
                                 attached_cells={})

        return None
        return FlyingMachine(flying_machine, origin,
                             mirrored=mirrored,
                             engine_cells=engine_cells,
                             pushed_cells={0: frozenset(group.cells)},
                             attached_cells={})
        # For attached blocks:
        # Next, we compute the clusters of the current group that are generated by inserting the engine in the group
        # at this place
        clusters = geode.compute_clusters(lambda cell: cell.group_nr == group.group_nr and cell not in engine_cells)

        cluster_lengths = {len(cluster) for cluster in clusters}
        footprint_set = set(flying_machine.attached_blocks.values())

        # If the clusters don't match the footprint subgroups of the attached blocks, we abort
        if cluster_lengths != footprint_set:
            return

        attached_cells: dict[int, frozenset[Cell]] = {}

        # If there is only one cluster, then all blocks can reach each other
        # --> ???
        if len(clusters) == 1:
            return

        # Cluster len >= 2
        for subgroup, groupsize in flying_machine.attached_blocks.items():
            # Cell attach points is not None because the attached footprint has the same
            # grid size as the engine footprint
            cell_attach_points: set[Cell] = FlyingMachine.footprint_to_cells(
                geode.grid, origin,
                flying_machine.attached_blocks_footprints[subgroup])

            # To determine whether we can connect the clusters to the attached cell groups, we
            # generate the frontier for a set of neighbouring cells
            attached_blocks_frontier = {cell
                                        for attach_point in cell_attach_points
                                        for cell in attach_point.neighbours
                                        if cell.group_nr == group.group_nr}

            # We can compute the intersection between the frontier and each cluster.
            # If it is not empty, the cluster can be attached to the current subgroup
            cluster = next((cluster
                            for cluster in clusters
                            if cluster & attached_blocks_frontier), None)
            if cluster is None:  # If no cluster matches the attached group, we abort
                # TODO: Do some cool shenanigans for non-full groups, else we abort too soon here
                return
            attached_cells[subgroup] = cluster
            clusters.remove(cluster)

        pushed_cells = {}  # Not yet implemented
        return FlyingMachine(flying_machine, origin,
                             mirrored=mirrored,
                             engine_cells=engine_cells,
                             pushed_cells=pushed_cells,
                             attached_cells=attached_cells)

    @staticmethod
    def footprint_to_cells(grid: list[list[Cell]],
                           origin: Cell,
                           footprint: list[list[Union[bool, Range]]],
                           mirrored: bool) -> Optional[set[Cell]]:
        footprint_cells = set()
        try:
            for row, row_val in enumerate(footprint):
                for col, val in enumerate(row_val):
                    if val:
                        footprint_cells.add(grid[origin.row + row][origin.col + (-col if mirrored else col)])
        except IndexError:
            return None
        return footprint_cells

    def __contains__(self, item):
        return item in self.complete_footprint

